### ISSUE TITLE
Missing db files

### ISSUE THREAD

**Issue by boneyag** [linzeqipku/drm_codesearch#1]
@linzeqipku , @laurence-ling :
When trying to prepare the data and train the model an error occurred.
```
~/PythonProjects/drm_codesearch$ python3 main.py -p --mode train
preparing dataset...
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main()
  File "main.py", line 47, in main
    prepare(conf, conf['data']['test_code_path'], conf['data']['test_nl_path'], conf['data']['test_db_path'], train_mode=False, train_db_path=conf['data']['train_db_path'])
  File "/home/akalanka/PythonProjects/drm_codesearch/preprocess/prepare.py", line 22, in prepare
    with open(train_corpus_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './tmp/train_origin_codevec.txt'
```
When I check the config.ini file the db paths are invalid because there are no db files in the `tmp` directory. How do I   generate/get the db files?

**Comment by laurence-ling** [comment]
@boneyag :
In the main.py file, line 45 and 46 are commented out.

` #prepare(conf, conf['data']['train_code_path'], conf['data']['train_nl_path'], conf['data']['train_db_path'], train_mode=True)`
`#prepare(conf, conf['data']['valid_code_path'], conf['data']['valid_nl_path'], conf['data']['valid_db_path'], train_mode=False, train_db_path=conf['data']['train_db_path'])`

Remove the comment and it will generate the db files for training and valid dataset.
